### ISSUE TITLE
 imageftbbox(): Could not set character size 

### ISSUE THREAD

**Issue by Brushez** [stil/gd-text#23] opened 2017-01-17 07:01 UTC
imageftbbox(): Could not set character size some of fonts when i test them 

error line `        return imageftbbox($this->getFontSizeInPoints(), 0, $this->fontFace, $text);
`

**Comment by stil** [comment] 2017-01-17 16:07
It might be font issue unrelated to gd-text library. Can you provide fonts that cause errors?

**Comment by Brushez** [comment] 2017-01-20 15:39
i don't know which font actually because i'm calling random posts for every time i refresh the page

**Comment by stil** [comment] 2017-01-20 19:17
It's very likely that your code has a bug. Are you sure you're setting correct font size every time?
I need a minimal code sample to reproduce your problem and confirm this issue exists.

**Comment by stil** [comment] 2017-02-10 14:09
Due to no feedback and being unable to reproduce problem, I'm closing this issue.

**Closed by stil** 2017-02-10 14:09 UTC
